services:
  db:
    image: postgres
    restart: unless-stopped
    stop_grace_period: 1s
    environment:
      - POSTGRES_PASSWORD=test
  
  nginx:
    image: nginx
    restart: unless-stopped
    stop_grace_period: 1s
    ports:
    - "80:80"
  
  