# Generated by Django 5.1 on 2024-08-22 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
                ('slug', models.CharField(max_length=52)),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tribes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('slug', models.CharField(max_length=21)),
                ('master', models.CharField(max_length=52)),
                ('parallel', models.CharField(max_length=21)),
                ('visibility', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(default=0)),
                ('curr_points', models.IntegerField(default=0)),
                ('prev_points', models.IntegerField(default=0)),
                ('campus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s21_tribe_tournaments.campuses')),
            ],
        ),
        migrations.CreateModel(
            name='Peers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('level', models.IntegerField()),
                ('wave', models.CharField(max_length=21)),
                ('curr_points', models.IntegerField(default=0)),
                ('prev_points', models.IntegerField(default=0)),
                ('campus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s21_tribe_tournaments.campuses')),
                ('curr_tribe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curr_tribe_id', to='s21_tribe_tournaments.tribes')),
                ('prev_tribe_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_tribe_id', to='s21_tribe_tournaments.tribes')),
            ],
        ),
    ]
