# Generated by Django 5.1 on 2024-11-05 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s21_tribe_tournaments', '0003_tournaments_campus_tournaments_tribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s21_tribe_tournaments.campuses'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='tribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s21_tribe_tournaments.tribes'),
        ),
    ]
