# Generated by Django 5.1 on 2024-11-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s21_tribe_tournaments', '0004_alter_tournaments_campus_alter_tournaments_tribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribes',
            name='master',
            field=models.CharField(blank=True, max_length=52),
        ),
    ]
