# Generated by Django 5.1 on 2024-11-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s21_tribe_tournaments', '0005_alter_tribes_master'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournaments',
        ),
    ]
